language: objective-c
cache: bundler
before_install:
  - brew update
  - brew upgrade xctool
script:
  - xctool -workspace tumitfahrer.xcworkspace -scheme tumitfahrer -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test
notifications:
  email: false

# whitelist
branches:
  only:
    - master
