language: objective-c
cache: bundler
before_install:
  - brew update
  - brew upgrade xctool
script:
  - xctool test -workspace tumitfahrer.xcworkspace -scheme tumitfahrer -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
  email: false
